version: '3.8'

services:
  starlink-analyzer:
    build: 
      context: https://github.com/Bitelectronics1/starlink_consumo.git
      dockerfile: Dockerfile
    container_name: starlink-data-analyzer
    ports:
      - "8501:8501"
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - STARLINK_PASSWORD=${STARLINK_PASSWORD}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      - starlink_logs:/app/logs
      - starlink_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - starlink-network

  starlink-daily-viewer:
    build: 
      context: https://github.com/Bitelectronics1/starlink_consumo.git
      dockerfile: Dockerfile
    container_name: starlink-daily-viewer
    ports:
      - "8502:8501"
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - STARLINK_PASSWORD=${STARLINK_PASSWORD}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      - starlink_logs:/app/logs
      - starlink_data:/app/data
    restart: unless-stopped
    command: ["python", "-m", "streamlit", "run", "src/web/daily_gb_viewer.py", "--server.port=8501", "--server.address=0.0.0.0"]
    networks:
      - starlink-network

networks:
  starlink-network:
    driver: bridge

volumes:
  starlink_logs:
  starlink_data:

